version: '3.1'

services:
  db:
    container_name: dio
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rocketseat
      POSTGRES_DB: dowhile
